apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: importthere
  description: Backstage component for importthere
  annotations:
    iap/app-info: "1/8a2e29c4-c6ac-4991-854b-1fe18d3a172c"
    github.com/project-slug: Miracle-6785/demo_import
    jenkins.io/job-full-name: importthere-org/importthere-job
    sonarqube.org/project-key: default/importthere
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-template: template:default/register-new-application
spec:
  type: service
  lifecycle: production
  owner: user:guest
